# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.


#NOTE: SET ALL OF THESE AS ENV VARIABLES WHEN THE TIME COMES
development:
  secret_key_base: ad8b443e184d5b5bc815890bd6bb0c9e3c7ea58db7fb9fad5de78d7a0e64a08f46f3cf7da331ce1d2e8e3b5ad5935b43d04acf62193ce77b24649056f6c83df1
  secret_key: sk_test_QBNOJDm3YOTAEaH0H55q5pWk
  STRIPE_PUBLIC_KEY: pk_test_OnPVvXIWYRWmkaiDKyM7vhd3
  STRIPE_SECRET_KEY: sk_test_QBNOJDm3YOTAEaH0H55q5pWk
  PHAXIO_KEY: 0be9d76743c7764610fb75f192223640d312b7fa
  PHAXIO_SECRET_KEY: 0e3a294107827ee52a5d32a7248a56e4204e6d50
  #PHAXIO_KEY: dc8f581e4c53690bdee6bcacefc92af880a8f103
  #PHAXIO_SECRET_KEY: 542086b4be25d57b8a32ccae7964f243ac374f95
  DOCRAPTOR_KEY: ydVvQdh5knSYuG8yZkS
  SENDGRID_USERNAME: app33286348@heroku.com
  SENDGRID_PASSWORD: ch54onoc  
  MANDRILL_USERNAME: ryanapower@gmail.com
  MANDRILL_PASSWORD: tvvhP082BA2bIGPyTrSDmg
  S3_BUCKET: swiftorders-logos
  AWS_ACCESS_KEY_ID: AKIAJT4Q7LFJVYNJWOIQ
  AWS_SECRET_ACCESS_KEY: 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

test:
  secret_key_base: ad8b443e184d5b5bc815890bd6bb0c9e3c7ea58db7fb9fad5de78d7a0e64a08f46f3cf7da331ce1d2e8e3b5ad5935b43d04acf62193ce77b24649056f6c83df1
  secret_key: sk_test_QBNOJDm3YOTAEaH0H55q5pWk
  STRIPE_PUBLIC_KEY: pk_test_OnPVvXIWYRWmkaiDKyM7vhd3
  STRIPE_SECRET_KEY: sk_test_QBNOJDm3YOTAEaH0H55q5pWk
  PHAXIO_KEY: 0be9d76743c7764610fb75f192223640d312b7fa
  PHAXIO_SECRET_KEY: 0e3a294107827ee52a5d32a7248a56e4204e6d50
  DOCRAPTOR_KEY: ydVvQdh5knSYuG8yZkS

staging: 
  secret_key_base: 9216dea8f4ee8b75a4472938fd8dab875eec20e87188bd312d6efc29c3bae4234b97e6cc32e597fab582ed6a457bc959928dd17a6d8134d86bd71c33d85eb340
  secret_key: sk_test_QBNOJDm3YOTAEaH0H55q5pWk
  STRIPE_PUBLIC_KEY: pk_test_OnPVvXIWYRWmkaiDKyM7vhd3
  STRIPE_SECRET_KEY: sk_test_QBNOJDm3YOTAEaH0H55q5pWk
  PHAXIO_KEY: dc8f581e4c53690bdee6bcacefc92af880a8f103
  PHAXIO_SECRET_KEY: 542086b4be25d57b8a32ccae7964f243ac374f95
  DOCRAPTOR_KEY: ydVvQdh5knSYuG8yZkS
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key: sk_test_QBNOJDm3YOTAEaH0H55q5pWk
  STRIPE_PUBLIC_KEY: <%= ENV["STRIPE_PUBLIC_KEY"] %>
  STRIPE_SECRET_KEY: <%= ENV["STRIPE_SECRET_KEY"] %>
  PHAXIO_KEY: dc8f581e4c53690bdee6bcacefc92af880a8f103
  PHAXIO_SECRET_KEY: 542086b4be25d57b8a32ccae7964f243ac374f95
  DOCRAPTOR_KEY: ydVvQdh5knSYuG8yZkS
