require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe FaxesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Fax. As you add validations to Fax, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FaxesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all faxes as @faxes" do
      fax = Fax.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:faxes)).to eq([fax])
    end
  end

  describe "GET show" do
    it "assigns the requested fax as @fax" do
      fax = Fax.create! valid_attributes
      get :show, {:id => fax.to_param}, valid_session
      expect(assigns(:fax)).to eq(fax)
    end
  end

  describe "GET new" do
    it "assigns a new fax as @fax" do
      get :new, {}, valid_session
      expect(assigns(:fax)).to be_a_new(Fax)
    end
  end

  describe "GET edit" do
    it "assigns the requested fax as @fax" do
      fax = Fax.create! valid_attributes
      get :edit, {:id => fax.to_param}, valid_session
      expect(assigns(:fax)).to eq(fax)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Fax" do
        expect {
          post :create, {:fax => valid_attributes}, valid_session
        }.to change(Fax, :count).by(1)
      end

      it "assigns a newly created fax as @fax" do
        post :create, {:fax => valid_attributes}, valid_session
        expect(assigns(:fax)).to be_a(Fax)
        expect(assigns(:fax)).to be_persisted
      end

      it "redirects to the created fax" do
        post :create, {:fax => valid_attributes}, valid_session
        expect(response).to redirect_to(Fax.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fax as @fax" do
        post :create, {:fax => invalid_attributes}, valid_session
        expect(assigns(:fax)).to be_a_new(Fax)
      end

      it "re-renders the 'new' template" do
        post :create, {:fax => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested fax" do
        fax = Fax.create! valid_attributes
        put :update, {:id => fax.to_param, :fax => new_attributes}, valid_session
        fax.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested fax as @fax" do
        fax = Fax.create! valid_attributes
        put :update, {:id => fax.to_param, :fax => valid_attributes}, valid_session
        expect(assigns(:fax)).to eq(fax)
      end

      it "redirects to the fax" do
        fax = Fax.create! valid_attributes
        put :update, {:id => fax.to_param, :fax => valid_attributes}, valid_session
        expect(response).to redirect_to(fax)
      end
    end

    describe "with invalid params" do
      it "assigns the fax as @fax" do
        fax = Fax.create! valid_attributes
        put :update, {:id => fax.to_param, :fax => invalid_attributes}, valid_session
        expect(assigns(:fax)).to eq(fax)
      end

      it "re-renders the 'edit' template" do
        fax = Fax.create! valid_attributes
        put :update, {:id => fax.to_param, :fax => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fax" do
      fax = Fax.create! valid_attributes
      expect {
        delete :destroy, {:id => fax.to_param}, valid_session
      }.to change(Fax, :count).by(-1)
    end

    it "redirects to the faxes list" do
      fax = Fax.create! valid_attributes
      delete :destroy, {:id => fax.to_param}, valid_session
      expect(response).to redirect_to(faxes_url)
    end
  end

end
